
  default: &default
    adapter: postgresql
    encoding: unicode
    host: localhost
    username: <%= ENV.fetch("DB_USER") { "postgres" } %>
    password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    port: 5432
  
  development:
    <<: *default
    database: <%= ENV["DB_NAME"] %>
    template: template0
  
  test:
    <<: *default
    database: <%= ENV["DB_NAME"] %>
    template: template0
  
  production:
    <<: *default
    database: <%= ENV["DB_NAME"] %>
    url: <%= ENV["DATABASE_URL"] %>
    template: template0
  